id = "ayla"
name = "Ayla"
grammar = "ayla"
path_suffixes = ["ayla", "ayl"]
scope = "source.ayla"

line_comments = ["//"]
multiline_comments = ["/*", "*/"]

language_servers = ["elen"]

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = '"', end = '"', close = true, newline = false }
]
